### ISSUE TITLE
node index error

### ISSUE THREAD

**Issue by dklombardo** [benmarten/CryptoETF#1]
API keys are entered:

TypeError: Cannot read property 'reduce' of undefined
    at Function.forEachPromise (CryptoETF-master/dist/PromiseUtils.js:26:20)
    at Function.getBalance (CryptoETF-master/dist/model/CoinbaseWallet.js:34:36)
    at CryptoETF-master/dist/index.js:32:58
    at <anonymous>
Error getting data, retrying..

**Comment by benmarten** [comment]
So guessing a bit in the dark, I think it could be two issues:
1) Node Version, I'm on v8.4.0; I haven't tested it on anything else... Can you double check that?
2) Settings format, can you check that you're accounts look like this:
https://github.com/benmarten/CryptoETF/blob/master/settings.example.json#L9
3) Try also running the source directly: 
`node --require babel-core/register src/sample.js` and `node --require babel-core/register src/index.js`

I hope it helps, let me know how it goes ;)

**Comment by dklombardo** [comment]
Node version 9.2.1

Settings are the correct

Running source directly produced same results as running 'node sample'

**Comment by benmarten** [comment]
its not the node version 9.2.1 works for me too...
Does the sample work for you?
`node --require babel-core/register src/sample.js`

**Comment by benmarten** [comment]
I just did a fresh clone, and a yarn install, it works for me out of the box, via `node index`. I didn't even build, or run the source....
Try this minimal `settings.json`:
```
{
  "accounts": {
    "poloniex": [],
    "coinbase": [{
      "apiKey": "RPU...",
      "apiSecret": "q4q..."
    }]
  },
  "symbolMapping": {},
  "otherHoldings": [],
  "options": {
    "rebalanceDeltaPct": 1.0
  }
}
```

**Comment by benmarten** [comment]
Actually I just found the bug.
Please leave: `"poloniex": [],` line in for now, if thats missing it crashes... Will fix that later today...
