### ISSUE TITLE
How do I add an exchange?

### ISSUE THREAD

**Issue by createthis** [benmarten/CryptoETF#21]
How do I add an exchange?

I'd like to add Cryptopia so I can view the current market price of HUSH: https://www.cryptopia.co.nz/api/GetMarket/5209

**Comment by benmarten** [comment]
Please take a look at this reference PR that adds another integration:
- https://github.com/benmarten/CryptoETF/pull/11/files
Essentially you need to add a new Integration under `src/model/integrations/` and add the api keys in the settings...

**Comment by createthis** [comment]
I got half way through this then realized the market price doesn't come from the exchange, but api.coinmarketcap.com. Thanks for the info! This can be closed.
