### ISSUE TITLE
Feature request: Exclude 0 or very small amount

### ISSUE THREAD

**Issue by fi0** [benmarten/CryptoETF#24]
Add an option to  exclude 0 or very small amount for the "Exchange" column

**Comment by benmarten** [comment]
May I understand why this would be useful?
The original intention of this tool is to show you where you're coins are. So if you even have the smallest fraction of a coin somewhere, it will show a value >0 in the amount column, and the respective exchange in its column.
For coins that you don't own, but the tool already knows that you could buy it at one of the exchanges based on your api settings, it will also show that one.

**Comment by fi0** [comment]
How about an extra column to show the exchanges that I own the coin?
The use case is, when I need to rebalance (sell), I'll need to know which exchanges to go to.

**Comment by benmarten** [comment]
#28 should address your concern ;)

**Comment by benmarten** [comment]
live in: https://github.com/benmarten/CryptoETF/releases/tag/1.6.1
