### ISSUE TITLE
Trouble installing pinkie-promise not found

### ISSUE THREAD

**Issue by h6y3** [benmarten/CryptoETF#27]
```
npm ERR! code E404
npm ERR! 404 Not Found: pinkie-promise@https://registry.npmjs.org/pinkie-promise/-/pinkie-promise-2.0.1.tgz
```

I believe it has to do with this:

https://github.com/floatdrop/pinkie-promise/issues/4

**Comment by benmarten** [comment]
Just tested it, works for me. What node version are u on?

**Comment by benmarten** [comment]
Try to remove node_modules and run npm install, or alternatively yarn install again ;)

**Comment by benmarten** [comment]
This might be related: http://blog.npmjs.org/post/169432444640/npm-operational-incident-6-jan-2018

**Comment by h6y3** [comment]
Cool - let me give it a shot, I'll let you know but assume it is fixed (hopefully).
