### ISSUE TITLE
BCH data from Coinbase showing incorrect balance

### ISSUE THREAD

**Issue by alexgpark** [benmarten/CryptoETF#29]
BCH is off by about 1 BCH.
All the other values it pulled in appear to be accurate, regardless of exchange.
Still throws off all the allocation %'s though :\

From CryptoETF:
<img width="297" alt="screen shot 2018-01-07 at 10 37 29 pm" src="https://user-images.githubusercontent.com/6458377/34661009-6dbb4bd0-f3fb-11e7-8cf2-cafbdf5ba956.png">

Actual:
![screen shot 2018-01-07 at 10 37 41 pm](https://user-images.githubusercontent.com/6458377/34661010-6dd36116-f3fb-11e7-9c50-b498fdf63070.png)

Can't isolate why this is the case only for BCH...any ideas?

**Comment by barryvdh** [comment]
Did you remove the BCH from the example settings? https://github.com/benmarten/CryptoETF/blob/master/settings.example.json#L51

**Comment by benmarten** [comment]
That should be it, please reopen, if issue persists ;)
