### ISSUE TITLE
TypeError when trying to run the sample

### ISSUE THREAD

**Issue by danishkhan** [benmarten/CryptoETF#33]
```
› node sample
Retrieving Coinmarketcap statistics...
TypeError: _Portfolio2.default.getOutput is not a function
```

Looking at https://github.com/benmarten/CryptoETF/blob/master/src/model/Portfolio.js there seems to be no `getOutput` function. Was that removed and should some other function be called there?

**Comment by benmarten** [comment]
Yes sorry, this is broken right now. It's already fixed in the develop branch though: https://github.com/benmarten/CryptoETF/commit/27d54ba0b279e441858b06fe19a4819e54ff56a3#diff-74828ca1f6cd74979b8cea54b3b679b7R24

**Comment by benmarten** [comment]
Fixed by https://github.com/benmarten/CryptoETF/releases/tag/1.6.2

**Comment by benmarten** [comment]
Fixed by
