### ISSUE TITLE
Contributing & Releases ;)

### ISSUE THREAD

**Issue by benmarten** [benmarten/CryptoETF#34]
Hi @barryvdh! I saw you pushed some commits directly to master. Unfortunately I had to revert them, pushing a new release...

I generally follow the git flow practice for this repo. Hence all new commit should go to the develop branch first. Then for a new release I follow this: https://github.com/benmarten/CryptoETF/blob/develop/README.md#releasing

This will create nice tags, and once the commit messages are in the conventional changeling style (https://www.npmjs.com/package/conventional-changelog-cli), they will show up nicely in the CHANGELOG: https://github.com/benmarten/CryptoETF/blob/master/CHANGELOG.md done via: https://github.com/benmarten/CryptoETF/blob/master/package.json#L30

So please feel free to commit your fixes again to develop. Unfortunately I lost them, after I realized they were in master.... Sorry about that ;)

**Comment by barryvdh** [comment]
So does everything need to be a new tag? 

I cant reproduce the color bug, but I've re-did the PR for Binance in #35 

I'll leave it up to you to tag/merge them then ;)
