### ISSUE TITLE
Ability to set allocation target manually

### ISSUE THREAD

**Issue by jorijnsmit** [benmarten/CryptoETF#40]
It would be a great addition if it were possible to setting the target allocation percentage per coin manually (through an array in `settings.json` maybe) instead of deriving it from the market share.

**Comment by benmarten** [comment]
Great idea!
I also thought about creating a Strategy class where we could implement different strategies, such as equalWeightStrategy, marketCapStrategy, manualStrategy... And so on... Adding this as a milestone ;)

**Comment by benmarten** [comment]
Solved by: https://github.com/benmarten/CryptoETF/releases/tag/1.8.0
